services:

  nginx:
    image: nginx:1.25
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/backend
      - ./frontend/dist:/var/www/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    ports:
      - "9134:5173"
    command: npm run dev -- --host 0.0.0.0

  postgres:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_USER: ${DB_USERNAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  queue:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: laravel_queue
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    depends_on:
      - backend
      - postgres
      - redis

volumes:
  pgdata:
