services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/backend
      - ./frontend/dist:/var/www/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    environment:
      APP_ENV: ${APP_ENV:-production}

  backend:
    build: ./backend
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: ${APP_ENV:-production}

  frontend:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "9134:5173"
    environment:
      APP_ENV: ${APP_ENV:-production}
    command: >
      sh -c "if [ \"$APP_ENV\" = 'development' ]; then npm run dev -- --host 0.0.0.0; else npm run build && tail -f /dev/null; fi"

  postgres:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_USER: ${DB_USERNAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  pgdata:
